### ISSUE TITLE
K8s OIDC Policy Resource: logout endpoint

### ISSUE THREAD

**Issue by shawnhankim** [nginx-openid-connect/nginx-oidc-kubernetes#3]
**Is your feature request related to a problem? Please describe.**
- Currently, the K8s NGINX OIDC policy contains the following properties:
  - Policy Resource:
    ```yaml
                oidc:
                  description: OIDC defines an Open ID Connect policy.
                  type: object
                  properties:
                    authEndpoint:
                      type: string
                    clientID:
                      type: string
                    clientSecret:
                      type: string
                    jwksURI:
                      type: string
                    redirectURI:
                      type: string
                    scope:
                      type: string
                    tokenEndpoint:
                      type: string
                    zoneSyncLeeway:
                      type: integer
    ```
  - OIDC Policy in K8s NGINX
    ```yaml
    apiVersion: k8s.nginx.org/v1
    kind: Policy
    metadata:
      name: oidc-policy
    spec:
      oidc:
        clientID: nginx-plus
        clientSecret: oidc-secret
        authEndpoint: https://keycloak.example.com/auth/realms/master/protocol/openid-connect/auth
        tokenEndpoint: http://keycloak.default.svc.cluster.local:8080/auth/realms/master/protocol/openid-connect/token
        jwksURI: http://keycloak.default.svc.cluster.local:8080/auth/realms/master/protocol/openid-connect/certs
        scope: openid+profile+email
    ```

- NGINX Plus OIDC additionally exposed the endpoints of user information and logout in the [PR](https://github.com/nginx-openid-connect/nginx-oidc-core-v1/issues/5). Hence they need to be added in the configuration file `k8s.nginx.org_policies.yaml` and codes (e.g. `nginx-oidc-kubernetes/*.go`)

**Describe the solution you'd like**
- Update `k8s.nginx.org_policies.yaml` and `oidc.yaml` to additionally complete the following configuration.
  - The URL for the user information endpoint of IdP.
  - The URL for the logout endpoint of IdP.
- Update `README.md`.
- Add the features in the following codes in `nginx-oidc-kubernetes/*.go`:
  - `virtualserver.go`
  - `http.go`
  - `nginx-plus.virtualserver.tmpl`
  - `types.go`
  - `policy.go`

**Describe alternatives you've considered**

**Additional context**
